### ISSUE TITLE
Github pages?

### ISSUE THREAD

**Issue by aynh** [yorsyd/yorsyd.github.io#1]
Nyalain GitHub pages mas biar langsung bisa dilihat di https://yorsyd.github.io/pweb

**Comment by yorsyd** [comment]
Keapa?

**Comment by aynh** [comment]
Di pengaturan repository cari Pages, ubah branch-nya ke main

**Comment by yorsyd** [comment]
ni udah lo yorsyd.github.io tapi css nya kd tesambung... keapa ni?

**Comment by aynh** [comment]
https://github.com/yorsyd/yorsyd.github.io/blob/f280e43745a7cf85cb479280b3e800a7b738df2c/dashboard.html#L20

Disini nama file CSS-nya style1.css, sementara CSS yang ada di folder ini namanya style.css

![2023-04-26-211542_916x185_scrot](https://user-images.githubusercontent.com/99479536/234587796-651dc9d4-b2da-4c89-b401-36b9e9495507.png)

**Comment by yorsyd** [comment]
![image](https://user-images.githubusercontent.com/91246717/234593417-f66490fb-4e99-46a5-94ee-39503ea55861.png)

**Comment by aynh** [comment]
Oh baiklah.

Btw GitHub pages hanya support website statis (HTML, CSS, JS) saja, jadi website dinamis yang pakai PHP itu tidak bisa.
